# Generated by Django 5.1.7 on 2025-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_cook_time_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
